-- CampusBridge schema: every table, in one file.
--
-- Runs against the H2 in-memory database (PostgreSQL compatibility mode) on every
-- startup via spring.sql.init; the database starts empty each time, so this file is
-- the whole schema, not a migration. data.sql runs after it with the mock data.
-- Hibernate still validates the @Entity classes against these tables
-- (ddl-auto: validate), so change an entity and you must change this file too.
--
-- Built from the former Flyway migrations V1, V4, V5, V6 and V7, in that order.

-- ===========================================================================
-- V1 baseline
-- ===========================================================================

-- Ordering: parents before children, so the foreign keys below resolve.

-- ---------------------------------------------------------------------------
-- Directory (plain JDBC, not JPA — Hibernate never sees these three)
-- ---------------------------------------------------------------------------

CREATE TABLE university (
    id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL UNIQUE
);

-- Column widths are deliberately generous. The previous H2 schema used
-- varchar(20) for names and varchar(40) for the city, which turned an ordinary
-- long surname into a 500 rather than a validation message.
CREATE TABLE student (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name        varchar(100) NOT NULL,
    last_name         varchar(100) NOT NULL,
    resident_city     varchar(100) NOT NULL,
    resident_state    varchar(2)   NOT NULL,
    university_id     bigint       NOT NULL REFERENCES university (id),
    grade             varchar(20)  NOT NULL,
    major             varchar(255) NOT NULL,
    -- One directory row per person: StudentRepository.findByEmail uses
    -- queryForObject, which throws on a second match.
    email             varchar(255) NOT NULL UNIQUE,
    social_media_link varchar(255)
);

CREATE INDEX idx_student_university ON student (university_id);

CREATE TABLE app_user (
    id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role     varchar(20)  NOT NULL,
    email    varchar(255) NOT NULL UNIQUE,
    -- Nullable since Clerk became the identity provider. Nothing reads it.
    password varchar(255)
);

-- ---------------------------------------------------------------------------
-- Marketplace
-- ---------------------------------------------------------------------------

CREATE TABLE listing (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_email varchar(255) NOT NULL,
    -- ADR-012 marketplace slice: the seller's Clerk subject; nullable until a legacy
    -- address-only row is claimed by its owner (identity-backfill.md rule 5).
    seller_subject varchar(255),
    title        varchar(255) NOT NULL,
    description  varchar(4000),
    category     varchar(255) NOT NULL,
    listing_type varchar(255) NOT NULL,
    status       varchar(255) NOT NULL,
    price        numeric(38, 2),
    course_code  varchar(255),
    school_id    bigint REFERENCES university (id) ON DELETE SET NULL,
    created_at   timestamp(6) with time zone NOT NULL,
    updated_at   timestamp(6) with time zone NOT NULL,
    CONSTRAINT listing_category_check CHECK (category IN
        ('BOOKS', 'CLOTHES', 'EVENT_TICKETS', 'FURNITURE', 'ELECTRONICS', 'OTHER')),
    CONSTRAINT listing_listing_type_check CHECK (listing_type IN
        ('SELL', 'RENT', 'FREE', 'LOOKING_FOR')),
    CONSTRAINT listing_status_check CHECK (status IN ('AVAILABLE', 'PENDING', 'SOLD'))
);

CREATE INDEX idx_listing_seller ON listing (seller_email);
CREATE INDEX idx_listing_seller_subject ON listing (seller_subject);
CREATE INDEX idx_listing_school ON listing (school_id);
CREATE INDEX idx_listing_status_category ON listing (status, category);
CREATE INDEX idx_listing_course_code ON listing (course_code);

CREATE TABLE listing_photo (
    listing_id bigint NOT NULL REFERENCES listing (id) ON DELETE CASCADE,
    photo_url  varchar(255)
);

CREATE INDEX idx_listing_photo_listing ON listing_photo (listing_id);

CREATE TABLE listing_favorite (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id bigint       NOT NULL REFERENCES listing (id) ON DELETE CASCADE,
    user_email varchar(255) NOT NULL,
    user_subject varchar(255),
    created_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT uk_listing_favorite UNIQUE (listing_id, user_email)
);

CREATE INDEX idx_listing_favorite_user ON listing_favorite (user_email);
CREATE UNIQUE INDEX uk_listing_favorite_subject ON listing_favorite (listing_id, user_subject);
CREATE INDEX idx_listing_favorite_user_subject ON listing_favorite (user_subject);

CREATE TABLE listing_report (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id     bigint        NOT NULL REFERENCES listing (id) ON DELETE CASCADE,
    reporter_email varchar(255)  NOT NULL,
    reporter_subject varchar(255),
    reason         varchar(1000) NOT NULL,
    created_at     timestamp(6) with time zone NOT NULL
);

CREATE INDEX idx_listing_report_listing ON listing_report (listing_id);

-- ---------------------------------------------------------------------------
-- Messages
-- ---------------------------------------------------------------------------

CREATE TABLE conversation (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type       varchar(255) NOT NULL,
    -- A conversation outlives the listing it started from.
    listing_id bigint REFERENCES listing (id) ON DELETE SET NULL,
    created_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT conversation_type_check CHECK (type IN ('MARKETPLACE', 'DIRECT'))
);

CREATE INDEX idx_conversation_listing ON conversation (listing_id);

CREATE TABLE conversation_participant (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id bigint       NOT NULL REFERENCES conversation (id) ON DELETE CASCADE,
    user_email      varchar(255) NOT NULL,
    -- ADR-012 messaging slice: the Clerk subject beside the address. Nullable while the
    -- email path still serves rows whose owner has not been seen since (identity-backfill.md
    -- rule 5); NULLs are distinct, so unbound rows never collide in the unique index.
    user_subject    varchar(255),
    unread_count    integer      NOT NULL,
    last_read_at    timestamp(6) with time zone,
    CONSTRAINT uk_conversation_participant UNIQUE (conversation_id, user_email)
);

CREATE INDEX idx_conversation_participant_user ON conversation_participant (user_email);
CREATE UNIQUE INDEX uk_conversation_participant_subject ON conversation_participant (conversation_id, user_subject);
CREATE INDEX idx_conversation_participant_subject ON conversation_participant (user_subject);

CREATE TABLE message (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id bigint        NOT NULL REFERENCES conversation (id) ON DELETE CASCADE,
    sender_email    varchar(255)  NOT NULL,
    sender_subject  varchar(255),
    content         varchar(4000) NOT NULL,
    image_url       varchar(255),
    created_at      timestamp(6) with time zone NOT NULL
);

CREATE INDEX idx_message_conversation ON message (conversation_id, created_at);

CREATE TABLE blocked_user (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blocker_email   varchar(255) NOT NULL,
    blocked_email   varchar(255) NOT NULL,
    blocker_subject varchar(255),
    blocked_subject varchar(255),
    created_at      timestamp(6) with time zone NOT NULL,
    CONSTRAINT uk_blocked_user UNIQUE (blocker_email, blocked_email)
);

CREATE UNIQUE INDEX uk_blocked_user_subject ON blocked_user (blocker_subject, blocked_subject);
CREATE INDEX idx_blocked_user_blocked_subject ON blocked_user (blocked_subject);

CREATE TABLE user_report (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_email   varchar(255)  NOT NULL,
    reported_email   varchar(255)  NOT NULL,
    reporter_subject varchar(255),
    reported_subject varchar(255),
    reason           varchar(1000) NOT NULL,
    created_at       timestamp(6) with time zone NOT NULL
);

CREATE INDEX idx_user_report_reported ON user_report (reported_email);
CREATE INDEX idx_user_report_reported_subject ON user_report (reported_subject);

-- ---------------------------------------------------------------------------
-- Community
-- ---------------------------------------------------------------------------

-- "group" is reserved in SQL, so the Group entity maps to app_group.
CREATE TABLE app_group (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             varchar(255) NOT NULL,
    description      varchar(2000),
    type             varchar(255) NOT NULL,
    related_value    varchar(255),
    school_id        bigint REFERENCES university (id) ON DELETE SET NULL,
    created_by_email varchar(255) NOT NULL,
    created_at       timestamp(6) with time zone NOT NULL,
    CONSTRAINT app_group_type_check CHECK (type IN
        ('MAJOR', 'GRADUATION_YEAR', 'COURSE_STUDY', 'GENERAL'))
);

CREATE INDEX idx_app_group_school ON app_group (school_id);

CREATE TABLE group_membership (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id   bigint       NOT NULL REFERENCES app_group (id) ON DELETE CASCADE,
    user_email varchar(255) NOT NULL,
    joined_at  timestamp(6) with time zone NOT NULL,
    CONSTRAINT uk_group_membership UNIQUE (group_id, user_email)
);

CREATE INDEX idx_group_membership_user ON group_membership (user_email);

CREATE TABLE post (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_email varchar(255)  NOT NULL,
    content      varchar(4000) NOT NULL,
    image_url    varchar(255),
    -- Null for the global feed; set for a post inside a group.
    group_id     bigint REFERENCES app_group (id) ON DELETE CASCADE,
    pinned       boolean       NOT NULL,
    created_at   timestamp(6) with time zone NOT NULL
);

CREATE INDEX idx_post_group ON post (group_id);
CREATE INDEX idx_post_created ON post (created_at DESC);

CREATE TABLE post_comment (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id      bigint        NOT NULL REFERENCES post (id) ON DELETE CASCADE,
    author_email varchar(255)  NOT NULL,
    content      varchar(2000) NOT NULL,
    created_at   timestamp(6) with time zone NOT NULL
);

CREATE INDEX idx_post_comment_post ON post_comment (post_id);

CREATE TABLE post_like (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id    bigint       NOT NULL REFERENCES post (id) ON DELETE CASCADE,
    user_email varchar(255) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT uk_post_like UNIQUE (post_id, user_email)
);

CREATE TABLE event (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title            varchar(255) NOT NULL,
    description      varchar(2000),
    location         varchar(255),
    starts_at        timestamp(6) with time zone NOT NULL,
    school_id        bigint REFERENCES university (id) ON DELETE SET NULL,
    listing_id       bigint REFERENCES listing (id) ON DELETE SET NULL,
    created_by_email varchar(255) NOT NULL,
    created_at       timestamp(6) with time zone NOT NULL
);

CREATE INDEX idx_event_starts_at ON event (starts_at);
CREATE INDEX idx_event_school ON event (school_id);

-- ---------------------------------------------------------------------------
-- Support
-- ---------------------------------------------------------------------------

CREATE TABLE support_resource (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id    bigint       NOT NULL REFERENCES university (id) ON DELETE CASCADE,
    name         varchar(255) NOT NULL,
    category     varchar(255) NOT NULL,
    description  varchar(2000),
    address      varchar(255),
    contact_info varchar(255),
    latitude     double precision,
    longitude    double precision,
    CONSTRAINT support_resource_category_check CHECK (category IN
        ('FOOD_PANTRY', 'EMERGENCY_AID', 'COUNSELING', 'OTHER'))
);

CREATE INDEX idx_support_resource_school ON support_resource (school_id);

CREATE TABLE anonymous_request (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_email varchar(255)  NOT NULL,
    category        varchar(255)  NOT NULL,
    description     varchar(2000) NOT NULL,
    status          varchar(255)  NOT NULL,
    school_id       bigint REFERENCES university (id) ON DELETE SET NULL,
    created_at      timestamp(6) with time zone NOT NULL,
    CONSTRAINT anonymous_request_category_check CHECK (category IN
        ('FOOD_PANTRY', 'EMERGENCY_AID', 'COUNSELING', 'OTHER')),
    CONSTRAINT anonymous_request_status_check CHECK (status IN ('OPEN', 'FULFILLED', 'CLOSED'))
);

CREATE INDEX idx_anonymous_request_school ON anonymous_request (school_id);

-- ===========================================================================
-- V4 student.clerk_user_id
-- ===========================================================================

-- S1-02 / ADR-012: the stable identity column.
--
-- Clerk email addresses are mutable, and 16 ownership columns across 13 tables key on
-- email, so an address change today orphans a student's listings, conversations, blocks
-- and posts. This is the stable key those columns migrate to in S1-10, S1-11 and S1-12.
--
-- Nullable on purpose. Every existing row stays valid, and NULL states the truth: nobody
-- has proved they own that row yet. The column is filled only when a Clerk subject
-- creates its own directory row (and, from S1-04, by the verified user.created webhook)
-- -- never by a bulk email match. That is what keeps the 33 fabricated V3 demo students
-- unbindable: they were seeded on plausible addresses such as sarah.johnson@mail.uc.edu,
-- and matching on email alone would hand a real student a fabricated profile.
--
-- No separate index: PostgreSQL implements UNIQUE with a btree index, so the constraint
-- below already serves lookups by clerk_user_id. NULLs are distinct in a unique
-- constraint, so any number of unbound rows coexist while a Clerk subject still owns at
-- most one student row.
--
-- Rules, options considered and the D-IDENTITY ballot: docs/phase-1/identity-backfill.md

ALTER TABLE student ADD COLUMN clerk_user_id varchar(255);

ALTER TABLE student ADD CONSTRAINT uk_student_clerk_user_id UNIQUE (clerk_user_id);

-- ===========================================================================
-- V5 clerk_identity
-- ===========================================================================

-- S1-04 / ADR-012: what Clerk's user.created webhook can actually record today.
--
-- The story asks the webhook to create the student row. It cannot, and this table is
-- the honest alternative rather than a silent redefinition of the requirement:
--
--   * `student` has seven NOT NULL columns a Clerk user event does not carry --
--     resident_city, resident_state, grade, major, university_id, and first/last name
--     (Clerk allows both to be null). Creating the row from an event means inventing
--     five values for a real person.
--   * university_id needs the domain-to-school mapping from S1-03, which does not exist
--     and is itself blocked on the unvoted D-SCHOOLS decision. Guessing a school is
--     exactly what that issue forbids.
--
-- So the webhook records the *identity* -- the verified Clerk subject and the address it
-- signed up with -- and the directory row is still completed by POST /student, which has
-- bound clerk_user_id since S1-02. That is the "pending profile" state: an account that
-- exists in Clerk and here, but has no directory row yet.
--
-- last_event_at makes the handler idempotent and order-safe without a separate ledger:
-- the upsert only advances a row when the incoming event is newer, so a Clerk retry is a
-- no-op and an out-of-order delivery cannot roll an address back. last_event_id is kept
-- for tracing a row back to the delivery that last wrote it.
--
-- No foreign key to student on purpose: the identity legitimately exists before the
-- directory row does, which is the whole point of the pending state.

CREATE TABLE clerk_identity (
    clerk_user_id varchar(255) PRIMARY KEY,
    email         varchar(255)               NOT NULL,
    last_event_id varchar(255)               NOT NULL,
    last_event_at timestamp(6) with time zone NOT NULL,
    created_at    timestamp(6) with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    timestamp(6) with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Finding the identity behind an address during profile completion.
CREATE INDEX idx_clerk_identity_email ON clerk_identity (email);

-- ===========================================================================
-- V6 profile fields
-- ===========================================================================

-- S1-06: the profile fields the directory, theming and community surfaces need.
--
-- Names and types follow the planned ERD accepted in S0-5 (docs/phase-0/erd-planned.mmd):
-- graduation_year integer, bio varchar, photo_url varchar.
--
-- All three are nullable. Every existing row predates them, and the contract asks for a
-- profile a student completes over time, not seven required fields at sign-up. A NOT NULL
-- here would mean inventing a default for 34 rows, including the fabricated V3 demo people.
--
-- Lengths, and why -- each one is mirrored by an @Size or @Min/@Max on the request objects,
-- because the defect this story exists to prevent is an over-length value reaching Postgres
-- and coming back as an opaque 500 from ExceptionTranslator's catch-all:
--
--   * bio varchar(1000) -- no recorded requirement sets this. 1000 is a few paragraphs,
--     enough for a self-description on a directory card and small enough that it can be
--     returned in a list response without bloating it. **A team decision could change it;
--     it is a chosen value, not a derived one.**
--   * photo_url varchar(255) -- matches the two URL columns already in the schema,
--     social_media_link and listing_photo.photo_url.
--   * graduation_year integer -- as the ERD has it. The request objects bound it to a
--     four-digit year; anything outside that is a typing error, not a student.
--
-- photo_url holds a reference, not an image. Constraining it to the approved asset host
-- so a student cannot point their profile at someone else's asset needs that host, which
-- is S1-05 (Cloudinary, decision 016, still Proposed). Until then the request objects
-- require https and bound the length, exactly as listing photos are bounded today.

ALTER TABLE student ADD COLUMN graduation_year integer;
ALTER TABLE student ADD COLUMN bio             varchar(1000);
ALTER TABLE student ADD COLUMN photo_url       varchar(255);

-- ===========================================================================
-- V7 profile privacy and images
-- ===========================================================================

-- S1-08 dependencies. Existing profiles have no privacy row and default private.
CREATE TABLE profile_privacy (
    student_id bigint PRIMARY KEY REFERENCES student(id) ON DELETE CASCADE,
    show_major boolean NOT NULL DEFAULT false,
    show_graduation_year boolean NOT NULL DEFAULT false,
    show_bio boolean NOT NULL DEFAULT false,
    show_photo boolean NOT NULL DEFAULT false
);

-- Record the provider id BEFORE upload, so even ambiguous/time-out outcomes can
-- be cleaned up. No provider credentials are stored here.
CREATE TABLE image_asset (
    id varchar(36) PRIMARY KEY,
    owner_subject varchar(255) NOT NULL,
    public_id varchar(255) NOT NULL UNIQUE,
    url varchar(255) UNIQUE,
    student_id bigint REFERENCES student(id) ON DELETE SET NULL,
    delete_after timestamp with time zone
);
CREATE INDEX idx_image_asset_cleanup ON image_asset(delete_after);
CREATE INDEX idx_image_asset_student ON image_asset(student_id);

