-- The supported institutions, carried over verbatim from the retired h2-data.sql
-- so school ids and names keep matching what the SPA and SupportResourceSeeder expect.
--
-- Eight rows, not six. Open Question 4 in context/5_progress.md is still unresolved:
-- the contract says "at least six", the sprint plan names six, this seed has eight.
-- Thomas More and Cincinnati Christian are the two in dispute. Resolve it with a
-- team vote, then add a migration that removes them — do not edit this file once it
-- has been applied.

INSERT INTO university (name) VALUES
    ('University of Cincinnati'),
    ('Northern Kentucky University'),
    ('Xavier University'),
    ('Miami University'),
    ('Thomas More University'),
    ('Cincinnati State Technical and Community College'),
    ('Mount St. Joseph University'),
    ('Cincinnati Christian University')
ON CONFLICT (name) DO NOTHING;
